feat: Adding Decorative + Shadow Colors / Fix Background.discount
Decathlon/vitamin-ios pull request #55
Opened 2022-03-16 10:50 UTC by baptistedajon

## Changes description
Adding Decorative + Shadow Colors / Fix Background.discount

## Context
Needed new colors for my project

## Checklist
- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on an iPhone device/simulator.
- [x] I have tested on an iPad device/simulator.

## Does this introduce a breaking change?
- No

2022-03-16 10:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Decathlon/vitamin-ios?pullRequest=55) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Decathlon/vitamin-ios?pullRequest=55) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Decathlon/vitamin-ios?pullRequest=55) it.</sub>

2022-03-17 13:38 UTC, daniel-dumortier requested changes
Great job ! 👍
I made just two little remarks : 
- I think the `backgroundDiscount` in Core and Light Themes should be kept as deprecated (they are public, even if their use is discouraged)
- I think the new `Shadow` semantic color should be used in the Shadow foundation

Since I made some of the changes also in another PR (for Tag implementation) because I needed them, I think that could be great if we merge this one first, then I'll merge main in my branch to resolve conflicts before merging it

2022-03-17 13:38 UTC, daniel-dumortier commented on Sources/Vitamin/Foundations/Colors/Semantic/Colors+Theme.swift
> +                public static let backgroundAlert = VitaminColor.Base.red400.color
Same than above

2022-03-23 11:49 UTC, florentlotthepro approved these changes
I've added some suggestions for deprecated warning.

2022-03-23 11:49 UTC, florentlotthepro commented on Sources/Vitamin/Foundations/Colors/Semantic/Colors+Theme.swift
> +                public static let backgroundDiscount = VitaminColor.Base.red400.color
`@available(*, deprecated, renamed: "backgroundAlert")`

2022-03-23 11:49 UTC, florentlotthepro commented on Sources/Vitamin/Foundations/Colors/Semantic/Colors+Theme.swift
> +                public static let backgroundDiscount = VitaminColor.Base.red400.color
`@available(*, deprecated, renamed: "backgroundAlert")`

2022-03-24 22:23 UTC, lauthieb commented
@baptistedajon feel free to fix conflicts.
Can you please take this opportunity by taking this issue: https://github.com/Decathlon/vitamin-ios/issues/23?
Thanks

2022-03-25 15:57 UTC, daniel-dumortier commented on Sources/Vitamin/Foundations/Colors/Semantic/Colors+Shadow.swift
> +    public enum Shadow {
fixed

2022-03-25 16:01 UTC, daniel-dumortier commented
@lauthieb : I made the last changes, resolved the conflicts, and integrated the missing refacto from #23 (some of them had already been integrated before)
I also linked the corresponding issues to this PR

Whenever @florentlotthepro or @baptistedajon approves, I will be able to merge it

@florentlotthepro : I did not write any new comment, there should be no typos this time ;)

2022-03-25 16:03 UTC, merged