feat(deployment_target): Update Deployment Target to iOS 12 + warning fixes
Decathlon/vitamin-ios pull request #83
Opened 2022-09-22 07:17 UTC by baptistedajon

## Changes description

Update deployment to target from iOS 10 to iOS 12 to be able to use Xcode 14.

## Context

Xcode 14 drops support for 32bits environnement (iOS 10) and iOS 12 supports every devices that iOS 11 does.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on an iPhone device/simulator.
- [x] I have tested on an iPad device/simulator.

## Does this introduce a breaking change?

- Yes
Vitamin iOS will not work in a project with a deployment target lower than iOS 12.

2022-09-22 15:57 UTC, florentlotthepro approved these changes

2022-09-23 11:58 UTC, daniel-dumortier approved these changes
Ok on principle, we'll just have to communicate well on next version that will have to be a 1.x

2022-10-11 16:52 UTC, florentlotthepro requested changes
We need to also update podspecs.

2022-10-13 14:44 UTC, florentlotthepro approved these changes

2023-03-14 21:23 UTC, lauthieb approved these changes

2023-03-16 14:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Decathlon/vitamin-ios?pullRequest=83) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Decathlon/vitamin-ios?pullRequest=83) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: baptistedajon<br/>:x: mackoj<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Decathlon/vitamin-ios?pullRequest=83) it.</sub>

2023-03-20 09:56 UTC, merged